Add missing Wayland dependency on BSDs (#1349)
src/display-wayland.cc:38:10: fatal error: 'sys/epoll.h' file not found
 #include <sys/epoll.h>
          ^~~~~~~~~~~~~

ld: error: undefined symbol: epoll_create1
>>> referenced by display-wayland.cc
>>>               src/CMakeFiles/conky.dir/display-wayland.cc.o:(conky::display_output_wayland::initialize())

ld: error: undefined symbol: epoll_ctl
>>> referenced by display-wayland.cc
>>>               src/CMakeFiles/conky.dir/display-wayland.cc.o:(conky::display_output_wayland::main_loop_wait(double))

ld: error: undefined symbol: epoll_wait
>>> referenced by display-wayland.cc
>>>               src/CMakeFiles/conky.dir/display-wayland.cc.o:(conky::display_output_wayland::main_loop_wait(double))